"""add session_id and position

Revision ID: ace2fc7fb532
Revises: 
Create Date: 2026-07-20 00:54:44.626757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace2fc7fb532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sets_user_id'))

    op.drop_table('user_sets')
    with op.batch_alter_table('problem_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_problem_attempts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_attempts_session_id'))
        batch_op.drop_column('position')
        batch_op.drop_column('session_id')

    op.create_table('user_sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=512), nullable=True),
    sa.Column('preview_text', sa.TEXT(), nullable=True),
    sa.Column('topic_ids', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.FLOAT(), nullable=True),
    sa.Column('question_count', sa.INTEGER(), nullable=True),
    sa.Column('hsc_relevance', sa.VARCHAR(length=20), nullable=True),
    sa.Column('course', sa.VARCHAR(length=20), nullable=True),
    sa.Column('analyzed_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
